version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      cargo-patches:
        patterns:
          - "*"
        update-types:
          - patch
      cargo-minors:
        patterns:
          - "*"
        update-types:
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
