use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::Read;
use std::path::Path;
use std::sync::{mpsc, Arc, Mutex};
use std::thread;
use std::time::Duration;

use anyhow::{Context, Result};
use rusqlite::Connection;

use crate::catalog::{finalize_catalog, CatalogFile, PackageEntry};
use crate::overrides::Overrides;
use crate::scan_eval::{self, Evaluated};

const SOURCE_V1: &str = "https://cdn.winget.microsoft.com/cache/source.msix";
const SOURCE_V2: &str = "https://cdn.winget.microsoft.com/cache/source2.msix";
const MANIFEST_BASE: &str = "https://cdn.winget.microsoft.com/cache/";

struct ManifestRef {
    id: String,
    #[allow(dead_code)]
    version: String,
    relative_path: String,
    index_commands: Vec<String>,
}

pub fn run_scan(out: &Path, overrides_path: &Path) -> Result<CatalogFile> {
    let overrides = Overrides::load(overrides_path)
        .map_err(|err| anyhow::anyhow!("reading overrides {}: {err}", overrides_path.display()))?;
    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(60))
        .user_agent("clevershim-scan")
        .build()?;
    let temp = std::env::temp_dir().join(format!("clevershim-scan-{}", std::process::id()));
    fs::create_dir_all(&temp)?;
    let v1 = temp.join("index-v1.db");
    let v2 = temp.join("index-v2.db");
    eprintln!("downloading WinGet source index");
    download_index(&client, SOURCE_V1, &v1)?;
    download_index(&client, SOURCE_V2, &v2)?;
    let refs = index_refs(&v1, &v2, &overrides)?;
    eprintln!("fetching {} installer manifests", refs.len());
    let bodies = fetch_manifests(&client, &refs);
    let mut packages = Vec::new();
    let mut meta: HashMap<String, (String, bool)> = HashMap::new();
    for item in &refs {
        let Some(body) = bodies.get(&item.id) else {
            continue;
        };
        let body = match body {
            Ok(text) => text,
            Err(err) if err.contains("HTTP 404") => {
                eprintln!("skip {}: {err}", item.id);
                continue;
            }
            Err(err) => anyhow::bail!("manifest for {} failed: {err}", item.id),
        };
        if let Some(version) = scan_eval::manifest_version(body) {
            meta.insert(
                item.id.to_ascii_lowercase(),
                (version, scan_eval::manifest_depend_flag(body)),
            );
        }
        if let Some(evaluated) = scan_eval::evaluate_manifest(body) {
            packages.push(evaluated_with_index_commands(
                evaluated,
                &item.index_commands,
            ));
        }
    }
    for include in &overrides.force_include {
        let key = include.id.to_ascii_lowercase();
        if let Some((version, depend)) = meta.get(&key) {
            if let Some(package) = packages
                .iter_mut()
                .find(|package| package.id.eq_ignore_ascii_case(&include.id))
            {
                package.archive_binaries_depend_on_path |= *depend;
                if package.version == "unknown" {
                    package.version = version.clone();
                }
            }
        }
    }
    let mut force = overrides.clone();
    for include in &mut force.force_include {
        if let Some((version, depend)) = meta.get(&include.id.to_ascii_lowercase()) {
            if include.version.is_none() {
                include.version = Some(version.clone());
            }
            include.archive_binaries_depend_on_path |= *depend;
        }
    }
    let catalog = finalize_catalog(packages, &force);
    if catalog.get("Gyan.FFmpeg").is_none() {
        anyhow::bail!("scan did not include Gyan.FFmpeg");
    }
    if catalog.get(crate::catalog::SELF_PACKAGE_ID).is_some() {
        anyhow::bail!("scan included {}", crate::catalog::SELF_PACKAGE_ID);
    }
    write_catalog(out, &catalog)?;
    eprintln!(
        "wrote {} packages and {} colliding commands to {}",
        catalog.packages.len(),
        catalog.collisions.len(),
        out.display()
    );
    let _ = fs::remove_dir_all(temp);
    Ok(catalog)
}

fn evaluated_with_index_commands(
    mut evaluated: Evaluated,
    index_commands: &[String],
) -> PackageEntry {
    for command in index_commands {
        evaluated.commands.insert(command.clone());
    }
    evaluated.into_package()
}

fn write_catalog(out: &Path, catalog: &CatalogFile) -> Result<()> {
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent)?;
    }
    let body = serde_yaml::to_string(catalog)?;
    let text =
        format!("# Generated by clevershim-scan from the public WinGet source index.\n{body}");
    fs::write(out, text)?;
    let collisions_path = out
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("collisions.yaml");
    let collisions = serde_yaml::to_string(&catalog.collisions)?;
    fs::write(
        collisions_path,
        format!("# Commands provided by more than one package.\n{collisions}"),
    )?;
    Ok(())
}

fn download_index(client: &reqwest::blocking::Client, url: &str, dest_db: &Path) -> Result<()> {
    let bytes = fetch_bytes(client, url)?;
    let cursor = std::io::Cursor::new(bytes);
    let mut archive = zip::ZipArchive::new(cursor).context("opening source.msix")?;
    let mut entry = archive
        .by_name("Public/index.db")
        .context("Public/index.db missing from source.msix")?;
    let mut file = fs::File::create(dest_db)?;
    std::io::copy(&mut entry, &mut file)?;
    Ok(())
}

fn index_refs(v1: &Path, v2: &Path, overrides: &Overrides) -> Result<Vec<ManifestRef>> {
    let latest = latest_versions(v2)?;
    let conn = Connection::open(v1)?;
    eprintln!("reading package index");
    let ids = load_text_map(&conn, "SELECT rowid, id FROM ids")?;
    let versions = load_text_map(&conn, "SELECT rowid, version FROM versions")?;
    let paths = load_paths(&conn)?;
    let commands = load_commands(&conn)?;
    let force: HashSet<String> = overrides
        .force_include
        .iter()
        .map(|include| include.id.to_ascii_lowercase())
        .collect();
    let mut stmt = conn.prepare("SELECT rowid, id, version, pathpart FROM manifest")?;
    let mut rows = stmt.query([])?;
    let mut chosen: HashMap<String, ManifestRef> = HashMap::new();
    while let Some(row) = rows.next()? {
        let manifest_id: i64 = row.get(0)?;
        let id_row: i64 = row.get(1)?;
        let version_row: i64 = row.get(2)?;
        let path_row: i64 = row.get(3)?;
        let Some(id) = ids.get(&id_row) else {
            continue;
        };
        let Some(version) = versions.get(&version_row) else {
            continue;
        };
        if latest.get(id).map(String::as_str) != Some(version.as_str()) {
            continue;
        }
        let index_commands = commands.get(&manifest_id).cloned().unwrap_or_default();
        if index_commands.is_empty() && !force.contains(&id.to_ascii_lowercase()) {
            continue;
        }
        let key = id.to_ascii_lowercase();
        let candidate = ManifestRef {
            id: id.clone(),
            version: version.clone(),
            relative_path: path_from(&paths, path_row),
            index_commands,
        };
        match chosen.get(&key) {
            Some(existing) if existing.index_commands.len() >= candidate.index_commands.len() => {}
            _ => {
                chosen.insert(key, candidate);
            }
        }
    }
    let mut refs: Vec<ManifestRef> = chosen.into_values().collect();
    refs.sort_by(|left, right| {
        left.id
            .to_ascii_lowercase()
            .cmp(&right.id.to_ascii_lowercase())
    });
    Ok(refs)
}

fn latest_versions(v2: &Path) -> Result<HashMap<String, String>> {
    let conn = Connection::open(v2)?;
    let mut stmt = conn.prepare("SELECT id, latest_version FROM packages")?;
    let rows = stmt.query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?;
    let mut versions = HashMap::new();
    for row in rows {
        let (id, version) = row?;
        versions.insert(id, version);
    }
    Ok(versions)
}

fn load_text_map(conn: &Connection, sql: &str) -> Result<HashMap<i64, String>> {
    let mut stmt = conn.prepare(sql)?;
    let rows = stmt.query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?;
    let mut map = HashMap::new();
    for row in rows {
        let (rowid, text) = row?;
        map.insert(rowid, text);
    }
    Ok(map)
}

fn load_paths(conn: &Connection) -> Result<HashMap<i64, (Option<i64>, String)>> {
    let mut stmt = conn.prepare("SELECT rowid, parent, pathpart FROM pathparts")?;
    let mut rows = stmt.query([])?;
    let mut map = HashMap::new();
    while let Some(row) = rows.next()? {
        map.insert(row.get(0)?, (row.get(1)?, row.get(2)?));
    }
    Ok(map)
}

fn load_commands(conn: &Connection) -> Result<HashMap<i64, Vec<String>>> {
    let mut stmt = conn.prepare(
        "SELECT cm.manifest, c.command FROM commands_map cm
         JOIN commands c ON c.rowid = cm.command",
    )?;
    let mut rows = stmt.query([])?;
    let mut map: HashMap<i64, Vec<String>> = HashMap::new();
    while let Some(row) = rows.next()? {
        map.entry(row.get(0)?).or_default().push(row.get(1)?);
    }
    Ok(map)
}

fn path_from(paths: &HashMap<i64, (Option<i64>, String)>, mut rowid: i64) -> String {
    let mut parts = Vec::new();
    let mut guard = 0;
    while guard < 64 {
        guard += 1;
        let Some((parent, part)) = paths.get(&rowid) else {
            break;
        };
        parts.push(part.clone());
        match parent {
            Some(next) if *next != 0 && *next != rowid => rowid = *next,
            _ => break,
        }
    }
    parts.reverse();
    parts.join("/")
}

fn fetch_manifests(
    client: &reqwest::blocking::Client,
    refs: &[ManifestRef],
) -> HashMap<String, Result<String, String>> {
    let jobs: Vec<(String, String)> = refs
        .iter()
        .map(|item| {
            (
                item.id.clone(),
                format!(
                    "{MANIFEST_BASE}{}",
                    encode_manifest_path(&item.relative_path)
                ),
            )
        })
        .collect();
    let queue = Arc::new(Mutex::new(jobs));
    let (tx, rx) = mpsc::channel();
    let workers = 24.min(refs.len().max(1));
    thread::scope(|scope| {
        for _ in 0..workers {
            let tx = tx.clone();
            let queue = Arc::clone(&queue);
            scope.spawn(move || loop {
                let next = queue.lock().ok().and_then(|mut jobs| jobs.pop());
                let Some((id, url)) = next else {
                    break;
                };
                let result = fetch_text(client, &url).map_err(|err| err.to_string());
                let _ = tx.send((id, result));
            });
        }
    });
    drop(tx);
    let mut done = 0usize;
    let total = refs.len();
    let mut bodies = HashMap::new();
    for (id, result) in rx {
        done += 1;
        if done.is_multiple_of(200) || done == total {
            eprintln!("manifests {done}/{total}");
        }
        bodies.insert(id, result);
    }
    bodies
}

fn encode_manifest_path(relative: &str) -> String {
    relative
        .split('/')
        .map(|segment| {
            let mut encoded = String::new();
            for byte in segment.bytes() {
                match byte {
                    b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                        encoded.push(byte as char);
                    }
                    _ => encoded.push_str(&format!("%{byte:02X}")),
                }
            }
            encoded
        })
        .collect::<Vec<_>>()
        .join("/")
}

fn fetch_text(client: &reqwest::blocking::Client, url: &str) -> Result<String> {
    let bytes = fetch_bytes(client, url)?;
    Ok(String::from_utf8_lossy(&bytes).into_owned())
}

fn fetch_bytes(client: &reqwest::blocking::Client, url: &str) -> Result<Vec<u8>> {
    let mut last_error = None;
    for attempt in 0..4 {
        if attempt > 0 {
            thread::sleep(Duration::from_millis(200 * attempt));
        }
        match client.get(url).send() {
            Ok(response) if response.status().is_success() => {
                let mut body = Vec::new();
                let mut response = response;
                response
                    .read_to_end(&mut body)
                    .context("reading response body")?;
                return Ok(body);
            }
            Ok(response) => {
                last_error = Some(anyhow::anyhow!("HTTP {} for {url}", response.status()));
            }
            Err(err) => last_error = Some(err.into()),
        }
    }
    Err(last_error.unwrap_or_else(|| anyhow::anyhow!("failed to fetch {url}")))
}
